iRNA-COSI/APAeval

docs/templates/snakemake/README.md
docs/templates/snakemake/config/[SAMPLES].csv
docs/templates/snakemake/config/config.[METHOD].yaml
docs/templates/snakemake/workflow/Snakefile

Partially fixes #189
First attempt at updating the Snakemake template to have flags in config to switch on/off output for each challenge.
To double check I had the syntax right I made a few modifications so that the template can successfully dry run. If you're sitting in the `snakemake` directory (`docs/templates/snakemake`), you can dry run with the following steps:
```
$ conda activate apaeval_execution_workflows
#2. Perform dry run
$ snakemake -n -p --configfile config/config.\[METHOD\].yaml
```
I've also made updates to the README accordingly, trying to mirror the Nextflow updates as much as possible (#196 - it would probably be easier if these were on the same PR...). I tried to remove any references to conda environments as we don't want our workflows to use these anymore.
Feedback …

Update Snakemake template & docs with 'run_<challenge>' flags

---

summary_workflows/quantification/APAeval_Q_test_data/data/Qx.json
summary_workflows/quantification/main.nf
summary_workflows/quantification/nextflow.config
summary_workflows/quantification/quantification_dockers/q_consolidation/OEB_aggr_query/OEB_aggr_query.py
summary_workflows/quantification/quantification_dockers/q_consolidation/aggregation.py
summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py

Fixes #236 
Previously only one window size was specified in config, thus, the workflow had to be re-run for different window sizes.   
- Provide list of window sizes in config
- loop over window sizes in `compute_metrics.py`
- create one aggregation object per plot per window size from template in `aggregation,py`

feat:several window sizes in one swf run

---

summary_workflows/quantification/README.md
summary_workflows/quantification/quantification_dockers/q_validation/validation.py

Improve validation in quantification summary workflow by comparing the chromosome names from the input against the list of chromosome names from the appropriate genome annotation. 
The genome annotation is now completely read, not only the first `n` lines. The code runs not much longer, I tested it on `gencode.hg38.v38.annotation.gtf`.
Fixes #258

feat: Validation with whole gtf

---

execution_workflows/DaPars/README.md
execution_workflows/DaPars/bin/check_input_params.py
execution_workflows/DaPars/bin/convert_output.py
execution_workflows/DaPars/conf/modules.config
execution_workflows/DaPars/modules/check_input_params.nf
execution_workflows/DaPars/modules/create_config_file.nf
execution_workflows/DaPars/modules/postprocess_relative_usage_quantification.nf
execution_workflows/DaPars/subworkflows/run_relative_usage_quantification.nf
execution_workflows/DaPars/workflow/execute_dapars.nf

Fixes #384
Workflow successfully ran to get relative usage quantification challenge output per sample.
Workflow:
Example output, the 5th column is the relative usage:

Execution workflow: DaPars - report Format 04 BED file in workflow (per-PAS fractional relative usage)

---

execution_workflows/DaPars/bin/check_bedgraph.py

Fixes #395 
We added a check to make sure the input files have 'chr' prefixes for all chromosomes. This was done to prevent Dapars from erroring out with a not so obvious error message when NO row contains 'chr' prefix. 
However, there are contigs in input files that by default contain to 'chr' prefix which we should allow. These row will be ignored by Dapars and we shouldn't be preventing the execution workflow from continuing by throwing an error when we encounter these rows. 
Our check should allow files containing non main chromosomes to pass without 'chr' prefix. These rows will be skipped by dapars by default. Our check should only make sure at least one row to have 'chr' prefix, as required by Dapars to not throw an error.

[Bug fix] Dapars: Skip 'chr' prefix check for non main chromosomes

---

execution_workflows/DaPars/bin/create_config_file.py

Fixes #397 
Config file creation in dapars is different depending on the run mode. Identification and relative usage quantification use the same type of config file, while differential uses a different type of config file. We added a new relative usage quantification run mode recently but this run mode is not reflected in config file creation. Instead, the differential run mode config file is created when we use relative usage quantification run mode. Hence, even though the workflow currently runs, the two parameters in the config file are incorrect:
Those two parameters in the config file for relative usage quantification should have looked this:
The fix is to add a run mode option 'relative_usage_quantification' in bin/create_config_file.py of dapars

[Bug fix] Dapars: fix config file creation for relative usage quantification run mode

---

execution_workflows/APAtrap/README.md
execution_workflows/APAtrap/bin/convert_to_bed.py
execution_workflows/APAtrap/conf/base.config
execution_workflows/APAtrap/modules/de_apa.nf
execution_workflows/APAtrap/modules/identify_distal_3utr.nf
execution_workflows/APAtrap/modules/predict_apa.nf

Fixes #402 
This PR solves two errors encountered when running APAtrap with real data.
1. When converting APAtrap output to absolute TPM quantification challenge output bed file, a column containing a list of TPMs is taken and parsed by splitting by comma. This column is known to contain strings and so is directly split by comma, which has worked for most of the datasets. 
However, while running APAtrap on one of the Keratinocyte samples, one row was written as int in the APAtrap output file while the rest were written as string as expected. Hence, this row caused the workflow to error out with the following message:
A solution for this is to always cast the rows to string before splitting as such:
2. APAtrap takes a long time when processing real datasets. Even when processing the …

[Bug Fix] APAtrap cast output to string before parsing and avoid time out error

---

execution_workflows/TAPAS/README.md
execution_workflows/TAPAS/bin/make_tapas_beds.py
execution_workflows/TAPAS/nextflow.config

Fixes #426 
Thanks to @mrgazzara for the POC below:
The raw output from TAPAS's first command APA_sites_detection based on their [readme instruction on their github page](https://github.com/arefeen/TAPAS) is relative abundance, which is read count normalized by the length of the 3UTR.
Relative usage quantification can be calculated by taking each of the relative abundance in the second to last column in the raw output (screenshot below) divided by the total relative abundance in the gene.
I ran this PR locally following the README using a subset of P19_siControl_R1 SRR6795721 data (using [test data](https://github.com/iRNA-COSI/APAeval/pull/391#issue-1311053632) provided by @SamBryce-Smith) with read_length set to 75 (based on the [data summary …

Execution workflow: TAPAS - report Format 04 BED file in workflow (per-PAS fractional relative usage)

---

summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py

Fixes #425 for the absolute Quantification challenge.
Changes in True positives
* The test files give the same values in _sensitivity_ , _precision_ and _jaccard index_
* For a real example, I used an older result of _Mayr_CD5B_R3_ on PAQR, I obtain more TP now. I guess this is because the TPM expression in the prediction can be > 0.

feat: unify TP calculation in aQ swf

---

summary_workflows/quantification/README.md
summary_workflows/quantification/main.nf
summary_workflows/quantification/nextflow.config
summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py

Fixes #424 
The filtering happens at two stages: 
- matched sites are filtered for prediction scores > `tpm_threshold`. This will be used for various metrics, including true positives and the various correlation metrics. 
- prediction sites are filtered for scores > `tpm_threshold`. This will be used for computing false positives.
Let me know if this makes sense in both cases.

SWF: include parameter to filter expression

---

execution_workflows/QAPA/bin/make_quant_bed.py

Fixes #436 
Thanks to @mrgazzara for reporting the bug!
**Problem**
An error occurred when running QAPA on Mayr data stating that string "NA" could not be converted to float in PPAU calculation.
**Solution**
A solution to this is when the PPAU value is NA, we leave the string as is. Otherwise, we convert PPAU value to float when calculating PPAU fraction.
The solution works

[BugFix] QAPA error converting string "NA" to float when calculating PPAU

---

execution_workflows/GETUTR/modules/getutr_process.nf
execution_workflows/GETUTR/modules/postprocessing_identification.nf
execution_workflows/GETUTR/subworkflows/run_getutr.nf

Fixes #438
**Background**
When running GETUTR with a huge sample file, postprocess step will encounter a file not found error from DaPars. An example of the error message is below:
This issue is however never encountered when using our test files that are small.
**Problem**
After investigating the workflow, the issue seems to be that getutr_process.nf publishes the file from GETUTR to a location in the output directory. The postprocessing step then reads from the file published to the output directory. When the output is big, the file publishing would take a little longer, but the workflow would already move on to the next process which is postprocessing step. Hence, the file is not found because it wasn't done being created.
**Solution**
One way to solve this is to avoid reading from a …

Bug: GETUTR file not found error in postprocessing step when using huge sample file

---

execution_workflows/IsoSCM/README.md
execution_workflows/IsoSCM/bin/check_samplesheet.py

Fixes #440 
**Background**
IsoSCM allows for two settings in terms for strandedness--unstranded and reverse_forward. It wasn't explicitly stated in the tool's README but when we have single end reads with reverse/forward strandedness, we can't set IsoSCM's strandedness to be reverse_forward. This will cause an error. Hence, we need to add checks in the workflow to prevent users from using the wrong combination of inputs and having to wait for the tool to run before encountering this error.
**Solution**
Add a parameter check when reading the samplesheet to never have reverse_forward and single read combination

Execution workflow update: IsoSCM doesn't run with reverse_forward and unstranded combination

---

execution_workflows/GETUTR/modules/postprocessing_identification.nf

Fixes a bug spotted by @dominikburri - GETUTR's identification output BED files were delimited by spaces not tabs, which doesn't fit the BED convention. I added a quick fix to the awk command to directly set the output delimiter to tab with `{OFS="\t"}`
e.g.
```
script:
identification_output = "${sample}_identification_output.bed"
"""
awk 'BEGIN {OFS="\t"} {if (\$1=="track") print \$0; else print \$1,\$2,\$3,\$4,".",\$6}' ${getutr_output} > ${identification_output}
"""
}
```
I ran with APAeval 2 gene test data and got tab-delimited output.
In example below I got vim to show hidden characters, with tabs denoted by '^I'.
If you also do a quick `head` on the output files you can also see that they appear to be tab-separated (top) vs the files generated with existing code (bottom)

Ewf bugfix: Change GETUTR challenge output file delimiter from space to tab

---

utils/metrics_json2tsv/metrics_json2tsv.py

When splitting metrics ids and expanding columns the script failed for identification jsons because some metrics don't contain window sizes, and there are no site sets in identification (script was written for AbsQuant files).   
Quick fix here: Replace `None` with mock value. Column `site_set` will contain mostly "NA", but "all" for metric AUC. This is necessary because pandas won't expand cols if there are only "NA" values.

Fix: utils metrics2tsv to work for identification event

---

summary_workflows/identification/identification_dockers/i_metrics/requirements.txt

Compute_metrics.py inside the i_metrics docker image failed because module sklearn not available.(had worked before)    
Fix: scikit-learn instead sklearn in requirements.txt

Fix: scikit-learn instead of sklearn

---

execution_workflows/GETUTR/Dockerfile
execution_workflows/GETUTR/README.md
execution_workflows/GETUTR/bin/postprocess_relative_quantification.py
execution_workflows/GETUTR/conf/modules.config
execution_workflows/GETUTR/modules/postprocessing_identification.nf
execution_workflows/GETUTR/modules/postprocessing_relative_quantification.nf
execution_workflows/GETUTR/subworkflows/run_getutr.nf

Fixes #450 
**Background**
GETUTR outputs 2 files - smoothed 3' UTR and poly(A) cleavage sites with relative usage per site. For identification challenge, we extract the output file containing poly(A) cleavage sites. An example of the output file is below:
**Solution**
For relative quantification challenge, we could take the column containing relative usage per site. We want a relative quantification challenge output file that looks like the following:
The name column includes a numbered suffix for each site to indicate the number of sites in each transcript.
Big thanks to @mrgazzara for the POC of this issue!
**Results**
After incorporating relative quantification workflow, the new execution workflow runs successfully:
The output files now contain both identification and relative …

Execution workflow: GETUTR - report Format 04 BED file in workflow (per-PAS fractional relative usage)

---

summary_workflows/identification/identification_dockers/i_metrics/compute_metrics.py

When dealing with big files, `compute_metrics.py` consumes a lot of memory and also takes very long to compute.
The reason for this is that for metric 5 computation, two list comprehensions are used to iterate over the genes in the genome. The output of the first list contains indices where a PAS was found. As this list is only used for computing how many PAS in a given gene are present, this does not need to be stored. 
The fix is to simply combine the two list comprehensions and only store the count of PAS per gene. This for sure decreases memory consumption and also should help in computation time.

fix: swf-ident: reduce memory and time consumption 

---

utils/apaeval/src/apaeval/main.py

The problem was that if the match within `bedtools_window` is empty, the dataframe was not correctly constructed and column names were not properly created. 
This caused a KeyError in `compute_metrics.py` when sorting the variable `matched`. 
The fix is to explicitly name the columns when creating the empty dataframe. 
The `else` statement is now extended to rename the columns from the non-empty (i.e. number of rows > 0) directly. 
I locally debugged the solution and it seems to work in that the variable `matched` is created with corresponding column names and the sorting successfully finishes. The metrics _sensitivity_ and _precision_ are evaluated to 0, as expected.

fix: deal with empty matched df

---

summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py

@ninsch3000 and I noticed when plotting scatter plots of correlation that the filtering by TPM threshold `-tpm` does not work as intended. 
The problem is that the function `split_pd_by_dist` can generate new prediction sites with score 0. The filtering was done prior to that though, so the matched dataframe ended up with 0 TPM scores even though the filter should remove them.
The fix is to move the filtering by TPM values to after modifying the matched object.
The function `merge_pd_by_gt` is not affected, since it would only merge and sum the expression from multiple prediction sites.

fix: filter on score only after matched modifications

---

utils/apaeval/setup.py

Fixes "no module named pyranges" error when running q_metrics container

pyranges in utils/apaeval setup

---

.gitignore
summary_workflows/JSON_templates/src/JSON_templates/main.py
summary_workflows/identification/identification_dockers/build.sh
summary_workflows/identification/identification_dockers/i_consolidation/aggregation.py
summary_workflows/identification/identification_dockers/i_consolidation/aggregation_template_I.json
summary_workflows/identification/identification_dockers/i_consolidation/merge_data_model_files.py
summary_workflows/identification/identification_dockers/i_metrics/compute_metrics.py
summary_workflows/identification/identification_dockers/i_metrics/constraints.txt
summary_workflows/identification/identification_dockers/i_metrics/requirements.txt
summary_workflows/identification/identification_dockers/i_validation/requirements.txt
summary_workflows/identification/identification_dockers/i_validation/validation.py
summary_workflows/identification/main.nf
summary_workflows/identification/nextflow.config
summary_workflows/identification/specification/I_benchmark_specification.md
summary_workflows/identification/specification/example_files/aggregation_out.json
summary_workflows/identification/specification/example_files/assessment_out.json
summary_workflows/quantification/main.nf
summary_workflows/quantification/nextflow.config
summary_workflows/quantification/quantification_dockers/build.sh
summary_workflows/quantification/quantification_dockers/q_consolidation/aggregation.py
summary_workflows/quantification/quantification_dockers/q_consolidation/aggregation_template_Q.json
summary_workflows/quantification/quantification_dockers/q_consolidation/merge_data_model_files.py
summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py
summary_workflows/quantification/quantification_dockers/q_metrics/requirements.txt
summary_workflows/quantification/quantification_dockers/q_validation/requirements.txt
summary_workflows/quantification/quantification_dockers/q_validation/validation.py
utils/README.md
utils/apaeval/main.md
utils/filter_jsons/filter_jsons.py

Fixes #459, #461, #462, #463
Currently our SWFs are not compatible with the OEB VRE infrastructure and must thus be run somewhere else. However, the output json files are supposed to comply with the OEB schemas, so that APAeval results can be uploaded into the OEB database and be visualized on the OEB website.   
In this PR the following changes have been made:
- specify correct time zone in `JSON_templates`, remove timestamp from manifest object
- for all `participant` objects, that is for all `validated_participant.challenge.json`, only save a single `participant` object that contains all challenge ids from all `validated_participant.challenge.json` in the `consolidated_results.json`.
- include objects from Manifest, containing participant and challenge ids, in …

fix: make SWF output jsons OEB compatible
