iRNA-COSI/APAeval

tests/test_data/README.md

feat: initialize directory for test data

---

LICENSE
README.md

docs: add code license

---

openebench/README.md
openebench/examples/challenge1.json
openebench/examples/contacts1.json
openebench/examples/metrics1.json
openebench/examples/references1.json
openebench/examples/tools1.json

feat: add OpenEBench schema examples

---

execution_workflows/README.md

Fixes #103 
Update table as is. Will create new issues for standardizing citation links and modify the installation column

feat: add method table

---

execution_workflows/README.md

docs: Fix execution workflow readme link to nextflow template example

---

apaeval_env.yaml

Currently, `apaeval_env.yaml` does not install Singularity. Running snakemake with the flag `-use-singularity` so can use Dockerfiles in a workflow produces the following error (I did this on the `DaPars2-snakemake` branch):
```
$ git branch 
* DaPars2-snakemake
$ pwd
/home/sam/GitHubRepos/APAeval/execution_workflows/DaPars2/Dapars2_snakemake
$ bash run_local.sh 
Building DAG of jobs...
WorkflowError:
The singularity command has to be available in order to use singularity integration.
File "/home/sam/miniconda3/envs/apaeval_execution_workflows/lib/python3.9/site-packages/snakemake/deployment/singularity.py", line 31, in __init__
```
Adding singularity to the `apaeval_env.yaml` env file resolves this dependency and fixes the above error.

Add singularity to execution workflows conda environment

---

execution_workflows/DaPars/bin/convert_output.py

Bug fix: Dapars parsing output with wrong cast to string

---

execution_workflows/DaPars/README.md
execution_workflows/DaPars/bin/check_input_params.py
execution_workflows/DaPars/bin/create_config_file.py
execution_workflows/DaPars/conf/modules.config
execution_workflows/DaPars/modules/convert_to_bedgraph.nf
execution_workflows/DaPars/modules/create_config_file.nf
execution_workflows/DaPars/modules/dapars_main.nf
execution_workflows/DaPars/modules/postprocessing_differential.nf
execution_workflows/DaPars/modules/postprocessing_identification.nf
execution_workflows/DaPars/subworkflows/preprocess_files.nf
execution_workflows/DaPars/subworkflows/run_differential.nf
execution_workflows/DaPars/subworkflows/run_identification.nf
execution_workflows/DaPars/workflow/execute_dapars.nf

Refactor DaPars to include mandatory run modes

---

execution_workflows/LABRAT/README.md
execution_workflows/LABRAT/bin/check_samplesheet.py
execution_workflows/LABRAT/bin/make_differential_tsv.py
execution_workflows/LABRAT/modules/labrat_calculatepsi.nf
execution_workflows/LABRAT/modules/labrat_maketffasta.nf
execution_workflows/LABRAT/modules/make_differential_tsv.nf
execution_workflows/LABRAT/modules/make_quant_bed.nf
execution_workflows/LABRAT/modules/salmon_index.nf
execution_workflows/LABRAT/modules/salmon_quant.nf
execution_workflows/LABRAT/nextflow.config
execution_workflows/LABRAT/subworkflows/run_labrat.nf
execution_workflows/LABRAT/workflow/execute_labrat.nf

This branch includes some fixes and enhancements to run LABRAT.
However, the changes are not complete and some more modifications are desired, see checklist below.

Ewf labrat extension

---

execution_workflows/DaPars/Dockerfile
execution_workflows/DaPars/main.nf
execution_workflows/DaPars/samplesheet_example_files_identification.csv

Update Dapars Dockerfile

---

summary_workflows/quantification/main.nf
summary_workflows/quantification/nextflow.config
summary_workflows/quantification/quantification_dockers/q_consolidation/aggregation.py

Small changes needed to make the summary workflow work on the VRE

Ag test swf in vre

---

summary_workflows/quantification/quantification_dockers/q_consolidation/aggregation.py
summary_workflows/quantification/quantification_dockers/q_consolidation/merge_data_model_files.py

Fix visualitzation

---

execution_workflows/PAQR/workflow/rules/create_tandem_pas.smk
execution_workflows/PAQR/workflow/rules/paqr.smk

use latest commits. Fixes #260.

---

summary_workflows/quantification/APAeval_Q_test_data/data/Qx.mm10.json
summary_workflows/quantification/README.md
summary_workflows/quantification/quantification_dockers/q_consolidation/aggregation_template_Q.json
summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py
summary_workflows/quantification/quantification_dockers/q_metrics/matchPAS/matchPAS.py
summary_workflows/quantification/specification/Q_benchmark_specification.md
summary_workflows/quantification/specification/example_files/aggregation_out.json
summary_workflows/quantification/specification/example_files/assessment_out.json

Fixes #326 
Had to duplicate the code for the different return statement of relative usage from #328, it is here in commit 60d05b15926578bedeb185c5aba0ffe25281552b. 
It is not nice but I wanted to keep one PR per issue. If a merge conflict should arise, I will fix it.

Add q metric spearman

---

summary_workflows/quantification/APAeval_Q_test_data/data/Qx.mm10.json
summary_workflows/quantification/quantification_dockers/q_consolidation/aggregation_template_Q.json
summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py
summary_workflows/quantification/quantification_dockers/q_metrics/matchPAS/matchPAS.py
summary_workflows/quantification/specification/Q_benchmark_specification.md
summary_workflows/quantification/specification/example_files/aggregation_out.json
summary_workflows/quantification/specification/example_files/assessment_out.json

include q metrics with different return df types

---

summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py
summary_workflows/quantification/quantification_dockers/q_metrics/matchPAS/matchPAS.py
summary_workflows/quantification/specification/Q_benchmark_specification.md

add metric Percent_non-matched-PAS to assessment,
add FP, FN and TP to restructured return value as dict
(instead of float).
Fixes #327

add percent unmatched

---

execution_workflows/QAPA/README.md
execution_workflows/QAPA/bin/make_quant_bed.py
execution_workflows/QAPA/modules/make_quant_bed.nf

report PPAU fraction from QAPA

---

summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py

fix: wrong indentation

---

execution_workflows/APAtrap/README.md
execution_workflows/APAtrap/bin/check_input_params.py
execution_workflows/APAtrap/bin/convert_to_bed.py
execution_workflows/APAtrap/conf/modules.config
execution_workflows/APAtrap/modules/convert_to_bed.nf
execution_workflows/APAtrap/workflow/execute_apatrap.nf

Execution workflows: Add per-PAS relative usage quantification BED file to APAtrap execution workflow

---

utils/apaeval/src/apaeval/main.py

Add filterPAS() function to the apaeval module

---

execution_workflows/TAPAS/nextflow.config

Fixes #442 
**Problem**
When running TAPAS on huge datasets, using docker often led to out of memory issues. (exit 137) However, using Singularity seemed more stable and the workflow didn't error out with out of memory issues
**Solution**
As such, add the option to run with Singularity for TAPAS workflow

Execution workflow update: enable Singularity option for TAPAS

---

summary_workflows/identification/identification_dockers/i_metrics/compute_metrics.py
summary_workflows/identification/identification_dockers/i_validation/validation.py
summary_workflows/identification/main.nf
summary_workflows/identification/nextflow.config
summary_workflows/quantification/main.nf
summary_workflows/quantification/nextflow.config
summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py
summary_workflows/quantification/quantification_dockers/q_validation/validation.py

Choose challenge more explicitly (to be able to distinguish e.g. R1 and R10); don't let nextflow overwrite assessments with rogue ones

Fix: SWF challenge selection

---

openebench/README.md
utils/README.md

docs: comment on filtering before OEB upload
